# Generated by Django 5.2.6 on 2025-10-18 15:18

import sliders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=sliders.models.upload_image)),
            ],
        ),
    ]
