# Generated by Django 5.2.6 on 2025-10-24 15:37

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=130)),
                ('address', models.TextField()),
                ('copy_right', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('instagram', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=settings.models.upload_image)),
            ],
        ),
    ]
