# Generated by Django 5.2.6 on 2025-11-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
