# Generated by Django 5.2.6 on 2025-11-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='visits',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
